version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  privileges:
    build:
      context: src/privileges
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    links: 
      - postgres
    restart: on-failure

  flights:
    build:
      context: src/flights
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    links: 
      - postgres
    restart: on-failure
  
  tickets:
    build:
      context: src/tickets
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    links: 
      - postgres
    restart: on-failure

  gateway:
    build:
      context: src/gateway
    ports:
      - "8080:8080"
    depends_on:
      - flights
      - privileges
      - tickets

volumes:
  db-data: